name: rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install up-to-date toolchain
      run: |
        rustup self update
        rustup toolchain update stable

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
