name: rust-clippy

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '38 18 * * *'

jobs:
  rust-clippy-analyze:
    name: Run Clippy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install up-to-date toolchain
        run: |
          rustup self update
          rustup toolchain update stable
          rustup component add clippy

      - name: Install required CLI tools (clippy-sarif and sarif-fmt)
        run: cargo install clippy-sarif sarif-fmt

      - name: Run Clippy
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
