name: rust-msrv

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install cargo-msrv
      run: cargo install cargo-msrv

    - name: Check msrv
      run: cargo msrv verify